spring:
  application:
    name: find-universities
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
io:
  github:
    alexcheng1982:
      agentappbuilder:
        chatagent:
          name: Query Universities
          description: Universities information
          usageInstruction: Ask me anything about universities