spring:
  application:
    name: find-universities
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
io:
  github:
    alexcheng1982:
      agentappbuilder:
        chatagent:
          name: Query Universities
          description: Universities information
          usageInstruction: Ask me anything about universities