/**
* Agent Protocol
* Specification of the API protocol for communication with an agent.
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.llmagentbuilder.launcher.ktor.server.models


/**
 * An Artifact either created by or submitted to the agent.
 * @param artifactId ID of the artifact.
 * @param agentCreated Whether the artifact has been created by the agent.
 * @param fileName Filename of the artifact.
 * @param relativePath Relative path of the artifact in the agent's workspace.
 */
data class Artifact(
    /* ID of the artifact. */
    val artifactId: kotlin.String,
    /* Whether the artifact has been created by the agent. */
    val agentCreated: kotlin.Boolean,
    /* Filename of the artifact. */
    val fileName: kotlin.String,
    /* Relative path of the artifact in the agent's workspace. */
    val relativePath: kotlin.String? = null
) 

