/**
* Agent Protocol
* Specification of the API protocol for communication with an agent.
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.llmagentbuilder.launcher.ktor.server.models


/**
 * 
 * @param message Message stating the entity was not found
 */
data class GetAgentTask404Response(
    /* Message stating the entity was not found */
    val message: kotlin.String
) 

