/**
* Agent Protocol
* Specification of the API protocol for communication with an agent.
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.github.llmagentbuilder.launcher.ktor.server.models

import io.github.llmagentbuilder.launcher.ktor.server.models.Pagination
import io.github.llmagentbuilder.launcher.ktor.server.models.Task

/**
 * 
 * @param tasks 
 * @param pagination 
 */
data class TaskListResponse(
    val tasks: kotlin.collections.List<Task>,
    val pagination: Pagination
) 

